alert_threshold: 2

alert_keywords:
  - fuel shortage
  - panic buying
  - delivery delays
  - rationing
  - no diesel

search_groups:
  - name: Fuel Station Disruption
    queries:
      - "fuel station closed site:news.com.au"
      - "no petrol OR no diesel Australia site:reddit.com/r/australia"
      - "fuel shortage Melbourne"

  - name: Freight Breakdown
    queries:
      - "truck delivery delays Australia"
      - "Coles Woolworths delivery delay"
      - "freight disruption Victoria"

  - name: Government Action
    queries:
      - "fuel reserve release site:dcceew.gov.au"
      - "fuel rationing announced site:abc.net.au"

  - name: Panic Buying
    queries:
      - "fuel price surge Australia"
      - "fuel panic buying OR fuel hoarding"

  - name: Regional Collapse
    queries:
      - "fuel shortage regional Australia"
      - "truck stop out of fuel"
